on: [push, pull_request]
name: Lint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install libpcap
        run: sudo apt-get install libpcap-dev
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
